### ISSUE TITLE
Please help me!!!

### ISSUE THREAD

**Issue by navaneethkm004** [bchiang7/v4#110]
I want to host it in Netlify or Repl.it. Please walk me through the necessary steps.

**Comment by GitHubEmploy** [comment]
Ok, I can help you.

1. Fork or clone this repo to another repository
2. Make a netlify account
3. Press the button on netlify that says, "new site from git".
4. Out of the 3 options now before you, click github
5. Then login with your github account
6. Then, out of your existing repos, search for the one you forked or cloned
7. Click on it and wait
8. The commands are already preset, although the build command should be "gatspy build". 
9. Press deploy site
10. Now, wait for it to build the site, then click on the link at the top-middle of the page to access the site

I hope this was helpful

**Comment by navaneethkm004** [comment]
Thank you very much!!!

**Comment by mding5692** [comment]
looks good, have a typo in build command by the way, should be `gatsby build` in step 8 @GitHubEmploy
