### ISSUE TITLE
How can I change the logo shown when loading?

### ISSUE THREAD

**Issue by navaneethkm004** [bchiang7/v4#111]

**Comment by navaneethkm004** [comment]
I want to put an N instead of B. How can I do it?

**Comment by GitHubEmploy** [comment]
You will have to set the logos manually.

**Comment by navaneethkm004** [comment]
Bro I changed all .png and .ico files to mine

**Comment by navaneethkm004** [comment]
But it's not changed when the website is starting

**Comment by pavanjadhaw** [comment]
Its svg which is being animated

`src/components/icons/logo.js`

this is the file you are interested in.

**Comment by GitHubEmploy** [comment]
Yeah, I am having the same problem, Idk how to fix this. Even though I changed the images and the paths, it still displays the old images. For me, it just took 10 minutes, and then it started working.

**Comment by navaneethkm004** [comment]
ohh! I will try and tell you. Thankss!!

**Comment by navaneethkm004** [comment]
No. It's still showing "B". Please respond @bchiang7 How can I change the logo which appears in the beginning, and also the logo in the left top after loading?

**Comment by bchiang7** [comment]
The loader is an SVG [here](https://github.com/bchiang7/v4/blob/main/src/components/icons/loader.js). The icon in the nav is also an SVG [here](https://github.com/bchiang7/v4/blob/main/src/components/icons/logo.js). I originally created these logos in Sketch and exported them as SVGs, but you can do something similar in any design tool.

**Comment by navaneethkm004** [comment]
Ohh! Thanks!!

**Comment by navaneethkm004** [comment]
Also which font did you use for the B

**Comment by bchiang7** [comment]
the same one in this repo

**Comment by navaneethkm004** [comment]
Oh okkk

**Comment by navaneethkm004** [comment]
But the prob is how can i make a logo in Windows 10. Sketch is Mac only!

**Comment by GitHubEmploy** [comment]
Yea, even though I have a mac, I am still confused about how to do this. Some advice would be helpful.

**Comment by bchiang7** [comment]
Like I said in my previous comment, I originally used Sketch, but you can export graphics as SVGs in any other design tool (Figma, photoshop, etc.)

**Comment by navaneethkm004** [comment]
Okayyy!! Thanks

**Comment by himanshu211raj** [comment]
You all do the same by replacing the path of logo with the below provided commands in both loader.js & logo.js file.

<text text-anchor="start" font-family="Calibre,system,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,Segoe UI,Arial,sans-serif" font-size="60" y="62" x="21" strokewidth="4" stroke="#64FFDA" fill="#64FFDA">(capital letter alphabet you want display as a logo)</text>

The above command is to be placed below <g transform line..

> The loader is an SVG [here](https://github.com/bchiang7/v4/blob/main/src/components/icons/loader.js). The icon in the nav is also an SVG [here](https://github.com/bchiang7/v4/blob/main/src/components/icons/logo.js). I originally created these logos in Sketch and exported them as SVGs, but you can do something similar in any design tool.

**Comment by navaneethkm004** [comment]
Thankssssss!!! I have not been able to make a proper svg till now. Thankss

**Comment by Abdalla1990** [comment]
I generated a new path with the letter A using the same font 
and i replaced the path in the SVG with the generated one.

**Comment by himanshu211raj** [comment]
> I generated a new path with the letter A using the same font
> and i replaced the path in the SVG with the generated one.

are u able to generate svg icons in png form by the method provided by me?

**Comment by navaneethkm004** [comment]
> > I generated a new path with the letter A using the same font
> > and i replaced the path in the SVG with the generated one.
> 
> are u able to generate svg icons in png form by the method provided by me?

Yesssss!! It's working perfectly!!

**Comment by navaneethkm004** [comment]
Thanks @himanshu211raj  for the help!!! Thank you all @Abdalla1990 @GitHubEmploy @himanshu211raj  for helping me out!!!

**Comment by navaneethkm004** [comment]
Thanks @himanshu211raj  for the help!!! Thank you all @Abdalla1990 @GitHubEmploy @himanshu211raj  for helping me out!!!

**Comment by GitHubEmploy** [comment]
<img width="67" alt="Screen Shot 2021-01-09 at 9 24 19 AM" src="https://user-images.githubusercontent.com/65371337/104104381-895d6400-525c-11eb-898f-aacdfa995750.png">
The new version of your fork is broken for certain letters.

**Comment by GitHubEmploy** [comment]
> You all do the same by replacing the path of logo with the below provided commands in both loader.js & logo.js file.
> 
> `<text text-anchor="start" font-family="Calibre,system,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,Segoe UI,Arial,sans-serif" font-size="60" y="62" x="21" strokewidth="4" stroke="#64FFDA" fill="#64FFDA">(capital letter alphabet you want display as a logo)</text>`
> 
> The above command is to be placed below <g transform line..
> 
> > The loader is an SVG [here](https://github.com/bchiang7/v4/blob/main/src/components/icons/loader.js). The icon in the nav is also an SVG [here](https://github.com/bchiang7/v4/blob/main/src/components/icons/logo.js). I originally created these logos in Sketch and exported them as SVGs, but you can do something similar in any design tool.

Also, the correct font name is Vayu Sans Extra Bold

**Comment by navaneethkm004** [comment]
oh. Okie!!

**Comment by chandrikadeb7** [comment]
@navaneethkm004 You can check this: https://youtu.be/-fIQy99I9wc
