### ISSUE TITLE
Adding Json file to read the static data.

### ISSUE THREAD

**Issue by amittttt** [bchiang7/v4#116]
I'm planning to add the static data in the json file.

Reason why I am planning to do:
-  when anyone wanted to host there personal website they just need to change that json file and portfolio is ready.
- Easy to modify details in the production (Need to change the Json file and we don't need to go for re-deployment)

@bchiang7 your thoughts? I am happy to work in this enhancement

**Comment by bchiang7** [comment]
Hi @amittttt, since my site isn't meant to be a template I'm going to say no thank you!
