### ISSUE TITLE
How to change color from cyan to something else?

### ISSUE THREAD

**Issue by navaneethkm004** [bchiang7/v4#122]
How to change color from the cyan color to green or something else? I want to change all the color including background. Pls reply @bchiang7

**Comment by bchiang7** [comment]
The green color is defined here https://github.com/bchiang7/v4/blob/main/src/styles/GlobalStyle.js#L19

**Comment by navaneethkm004** [comment]
Nonono I meant how to change to any color. Not only green but any color. I tried changing by changing hex code but it's not changing in the site. But I've put it on auto update mode in Netlify but it updates and nothing happens. Can I add a color in Global Style? Also pls help to change the color to any color. I just said an example.
