### ISSUE TITLE
Sorry but how to change color to any color? 

### ISSUE THREAD

**Issue by navaneethkm004** [bchiang7/v4#123]
Nonono I meant how to change to any color. Not only green but any color. I tried changing by changing hex code but it's not changing in the site. But I've put it on auto update mode in Netlify but it updates and nothing happens. Can I add a color in Global Style? Also pls help to change the color to any color. I just said an example.

Sorry for reopening the issue.

**Comment by bchiang7** [comment]
Yes, all the colors are defined as CSS variables in GlobalStyle.js https://github.com/bchiang7/v4/blob/main/src/styles/GlobalStyle.js#L10-L20

When you update GlobalStyle.js, you need to manually refresh the page locally to see your changes, hot reload will not apply updates to GlobalStyle.

**Comment by navaneethkm004** [comment]
Oh. Thanks for the tip. I'll try it and tell the results.
