### ISSUE TITLE
Plagiarism form

### ISSUE THREAD

**Issue by HariAcidReign** [bchiang7/v4#125]
### Quick suggestion time
Do consider making a Google Form where ppl can post URLs of other people's websites where credit has not been given so that you can contact them and request them to if you want

Personally, I've seen tens of portfolio sites that say "Created and Developed by <their name>" even though it's not the case

**Comment by bchiang7** [comment]
Hey @HariAcidReign, thanks for the suggestion, but I'm not interested.
