### ISSUE TITLE
Nice site!

### ISSUE THREAD

**Issue by SimonPaul02** [bchiang7/v4#126]

**Comment by chandrikadeb7** [comment]
> Hello, you have built a really nice site! I want to run it on my own pc to modify it, but I can't find the index.html file. I am really new to web dev, so could you please tell me how to run the side locally?

You can refer this video: https://youtu.be/EdlGgn9uhPU

**Comment by Sunilkumarchoudari** [comment]
> Hello, you have built a really nice site! I want to run it on my own pc to modify it, but I can't find the index.html file. I am really new to web dev, so could you please tell me how to run the side locally?

She has mentioned everything, and web development completly based on javascript.....  simply install npm,nodejs,gatsby plugins, and build the static ..... one thing gatsby, nodejs higher than 10v
