### ISSUE TITLE
Possibility of dynamically generating resume. 

### ISSUE THREAD

**Issue by esirK** [bchiang7/v4#129]
Firstly, thank you for building such an amazing website.

I was wondering/hoping if it would be possible to dynamically generate a resume instead of having a hardcoded one in a folder. I've started trying to do such an implementation using [PDFKIT](https://github.com/foliojs/pdfkit). Do you think it's a feature you could add to the website?

**Comment by bchiang7** [comment]
Hey @esirK, since my site & resume aren't designed to be templates, I'd rather not. Thanks!
