### ISSUE TITLE
Insert blog using graphQL with Gatsby

### ISSUE THREAD

**Issue by jonas-kgomo** [bchiang7/v4#14]
I would like to have a blog index in this website, where you can see a list of recent blogs. Essentially reading Markdown in new page

**Comment by bchiang7** [comment]
Sorry, but I'm not taking any feature requests -- this is my personal site, not a template, so feel free to fork it if you would like to add to it!

**Comment by jonas-kgomo** [comment]
I want to thank you for this project, I used Gatsby Markdown to do the [blog](http://jonas-kgomo.github.io/). This has helped me in my career.
