### ISSUE TITLE
For links in the Hero `hero.js` section, the cursor shows as pointer, not external link

### ISSUE THREAD

**Issue by RuolinZheng08** [bchiang7/v4#144]
Firstly thanks for this wonderful template!

![link](https://user-images.githubusercontent.com/35674052/122614263-307bce00-d03b-11eb-827c-40594a817c53.gif)

Adding `target=_blank` seems to tag it as an external link and shows the correct external-link cursor.

```html
Currently, I'm an engineer at{' '}
<a href="https://upstatement.com/" target='_blank'>Upstatement</a> focused on building accessible,
human-centered products.
```

**Comment by bchiang7** [comment]
Fixed in #145!
