### ISSUE TITLE
Lightning resume integration

### ISSUE THREAD

**Issue by oxmanroman** [bchiang7/v4#157]
Hey Brittany! First of all, your resume rocks 🎸 

I see many people are forking your resume in order to build their own, the issue is that it might take some time to adjust your template to each person exact needs, and then maintaining it while as well maintaining their LinkedIn profile.

Me and @chekuda came up with [Lightning resume](https://github.com/lightning-resume/lightning-resume), a tool that would allow anyone to create a resume website like yours in about **20 seconds** 😮 

We wanted to know what you think, and if you would be okay for us to adapt and use your resume as a template in Lightning resume.

We would add a footer that would say something like `Template from Brittany Chiang. Generated with ⚡ Resume.`

Looking forward to hearing your thoughts, it would great if you could try it out. We currently have only one basic template called `navy`

**Comment by bchiang7** [comment]
Hey @oxmanroman, since I didn't originally intend for this site to be a template, I'm going to politely decline. Cool tool though! Best of luck with it.
