### ISSUE TITLE
Should I replace all the name and emails in the project with mine?

### ISSUE THREAD

**Issue by kave-me** [bchiang7/v4#163]
Hello, recently I cloned this repo, I intend to make it personalized to my need, I replace all the occurrences of your name and email with mine but I doubt is it the right thing to do?! I think there are cases in the project that I should not touch.

Please just give me the name of the files or a rule that I can figure out the name of the files in which I should not replace them.
Thanks in advance

**Comment by xMdb** [comment]
its fine
![image](https://user-images.githubusercontent.com/46137770/135222481-76a7d8b2-74da-4183-8560-2f43500ec26c.png)

**Comment by kave-me** [comment]
I Still don't know what to keep and what to replace, and I don't want to trust my gut feeling in this issue, so please just tell me [fileName:lineNumber]

![screenshot-github com-2021 09 30-06_02_05](https://user-images.githubusercontent.com/27765198/135376298-ae95a7f0-e0e1-4a0a-81eb-6c185e29320f.png)

**Comment by OladapoAjala** [comment]
Hello, @kave-me I believe you can change whatever section of the project you desire to change. However when you are done working on the project give Brittany Chiang credit for designing the entire project. 

You can replace any section of the project you desire to replace.

**Comment by danlourenco** [comment]
@kave-me -- I don't see any attribution on your site back to Brittany.  You should really correct that.
