### ISSUE TITLE
Npm install not working

### ISSUE THREAD

**Issue by autosaver** [bchiang7/v4#181]
![image](https://user-images.githubusercontent.com/54054645/149546937-3077eba4-b995-48a0-9fbb-83c79d3a3ec8.png)

I am getting on npm install on my windows 11 (64bit).

**Comment by bchiang7** [comment]
This project uses yarn as a package manager, not npm. Try `yarn` instead of `npm install`

**Comment by autosaver** [comment]
Thanks its working now
