### ISSUE TITLE
Hide projects section

### ISSUE THREAD

**Issue by hardcore** [bchiang7/v4#193]
Hi @bchiang7 ,

thanks a lot for your code! How can I hide the "projects" section in the code?

Thanks a lot :-)

**Comment by bchiang7** [comment]
You could just comment out this line https://github.com/bchiang7/v4/blob/main/src/pages/index.js#L17

**Comment by hardcore** [comment]
Thanks a lot! :-)

One last question: How is it possible to change the logo at the top and the logo at the loading screen?

Thanks you very much!

**Comment by manitbaser** [comment]
@hardcore you'll have to update the following files for this as per your need:
```
src/components/icons/loader.js
src/components/icons/logo.js
```
Hope it helps!

**Comment by hardcore** [comment]
Thanks a lot @manitbaser
