### ISSUE TITLE
ERROR: MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by iamshobhitkumar** [bchiang7/v4#197]
(node:22664) MaxListenersExceededWarning: Possible EventEmitter memory leak     
detected. 11 end listeners added to [PassThrough]. Use emitter.setMaxListeners()
 to increase limit

 Not able to fix this error while building.

**Comment by ELELUABDULSALAM** [comment]
How are you able to solve this

**Comment by ELELUABDULSALAM** [comment]
@iamshobhitkumar

**Comment by sahityadubey** [comment]
@iamshobhitkumar what is the solution for this?
