### ISSUE TITLE
div blocking card highlight

### ISSUE THREAD

**Issue by dumblole** [bchiang7/v4#20]
![image](https://user-images.githubusercontent.com/28949652/61177006-13aa0680-a599-11e9-9c62-7e265c946510.png)

The highlighted div blocks onhover for the card. Just wanted to let you know if this isn't intended.

Great job on the site, it looks really nice.

**Comment by bchiang7** [comment]
Thanks for pointing this out, I never noticed! [Fixed](https://github.com/bchiang7/v4/commit/9b01f62c2de24cfa0418833c6de3dc1740182954)
