### ISSUE TITLE
Can I do that?

### ISSUE THREAD

**Issue by Johann-Goncalves-Pereira** [bchiang7/v4#226]
I like your website, so I make my website following your Design, but I don't use anything from your code. I made my on Html/Css and I don't even use JavaScript.

I gave you credit on my repository and in my site.

So see if everything is ok.

- [Repo](https://github.com/Johann-Goncalves-Pereira/RJP)
- [Website](https://johann-goncalves-pereira.netlify.app)

**Comment by codeapplied** [comment]
I think you shouldn't be worried if you say that you did everything.
