### ISSUE TITLE
other projects are not showing

### ISSUE THREAD

**Issue by MahendraBishnoi29** [bchiang7/v4#231]
Below projects section other noteworthy projects are not showing: 

![Screenshot (178)](https://user-images.githubusercontent.com/74294202/189479405-99ab58d7-7e13-4db7-86db-bc00386a7c63.png)

`projects` file:

<img width="476" alt="Screenshot 2022-09-10 160234" src="https://user-images.githubusercontent.com/74294202/189479458-c2e3bf27-9f04-4d0b-8ad0-75fc52a8a44e.png">

**Comment by MahendraBishnoi29** [comment]
@hichemfantar @bchiang7 @gupta-ji6 please help me out.

**Comment by hichemfantar** [comment]
Hello, you're supposed to set `showInProjects: true` in the project's markdown.

**Comment by MahendraBishnoi29** [comment]
> Hello, you're supposed to set `showInProjects: true` in the project's markdown.

thank you 😃

**Comment by hichemfantar** [comment]
You're welcome. You may close this issue if your problem is solved.

**Comment by MahendraBishnoi29** [comment]
hey @hichemfantar how do i change logos? like favicon, pre loader.

**Comment by hichemfantar** [comment]
You can start by looking at this file: https://github.com/bchiang7/v4/blob/main/src/components/head.js

**Comment by MahendraBishnoi29** [comment]
> You can start by looking at this file: https://github.com/bchiang7/v4/blob/main/src/components/head.js

I've already discovered this file but how do I change the svg's and logos exactly?

**Comment by hichemfantar** [comment]
You can simply replace these images with yours. `Src/images/`

**Comment by MahendraBishnoi29** [comment]
sir i how to i create logos like these ?
![logo](https://user-images.githubusercontent.com/74294202/189520256-d1a47efd-cef3-474b-a821-b3be3f477c79.png)

**Comment by hichemfantar** [comment]
You can use something like adobe photoshop or illustrator. Or u can use a free online service like Pixlr.

**Comment by MahendraBishnoi29** [comment]
> You can use something like adobe photoshop or illustrator. Or u can use a free online service like Pixlr.

I've replaced logo.png file but still the nav logo is not changing?

<img width="175" alt="Screenshot 2022-09-12 113216" src="https://user-images.githubusercontent.com/74294202/189584309-72e94d70-d5bb-4844-bfb2-3d206f8715a1.png">

**Comment by hichemfantar** [comment]
I honestly don't remember exactly which files should be edited.
But I suggest replacing all logos and images with your own.

**Comment by MahendraBishnoi29** [comment]
> I honestly don't remember exactly which files should be edited. But I suggest replacing all logos and images with your own.

already did but not working that's why i'm asking here :(

**Comment by hichemfantar** [comment]
Try clearing the Gatsby cache folder

**Comment by sujanshresstha** [comment]
> 

Try to change  icon.js file inside src/components/icon directory.

**Comment by sujanshresstha** [comment]
> > I honestly don't remember exactly which files should be edited. But I suggest replacing all logos and images with your own.
> 
> already did but not working that's why i'm asking here :(

Try to change logo.js file inside src/components/icon directory.

**Comment by MahendraBishnoi29** [comment]
> > > I honestly don't remember exactly which files should be edited. But I suggest replacing all logos and images with your own.
> > 
> > already did but not working that's why i'm asking here :(
> 
> Try to change logo.js file inside src/components/icon directory.

hey how did you created that preloader?

**Comment by sujanshresstha** [comment]
@MahendraBishnoi29
 Brittany Chiang already did magic with animation, i have just played with the svg.

**Comment by sujanshresstha** [comment]
@MahendraBishnoi29
Brittany Chiang already did magic with animation, i had just played with the svg.

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29
> Brittany Chiang already did magic with animation, i had just played with the svg.

can you please tell me how to draw M?

**Comment by hichemfantar** [comment]
@MahendraBishnoi29 You should close this issue and open a different one for your new issue.
