### ISSUE TITLE
Query regard Using This Template

### ISSUE THREAD

**Issue by Tanmoy741127** [bchiang7/v4#246]
I am currently building an open source platform where developers can create and manage their portfolio and switch between templates easily.
I like this design.

Can I integrate this in the platform ?
Proper source code link of this github repo and author's name will be mentoned under template .

**Comment by Tanmoy741127** [comment]
@bchiang7 can you share your thought ?

**Comment by Tanmoy741127** [comment]
@bchiang7  can you share your thought ?

**Comment by bchiang7** [comment]
Sorry, but I'd prefer if you didn't. I did not build my site with the intention of it being a template, even if it has turned into that over the years!

**Comment by Tanmoy741127** [comment]
@bchiang7 ok no issue.
Thanks for the confirmation.
