### ISSUE TITLE
Project not installing correctly

### ISSUE THREAD

**Issue by hedevelope** [bchiang7/v4#253]
I checked every node versions but same result.
![image](https://user-images.githubusercontent.com/46059951/218450906-e3a0f889-2f7a-4de6-8ea8-a560b44cdb8c.png)

**Comment by hedevelope** [comment]
This is vercel btw

**Comment by heyanilthakur** [comment]
Did you solved the issue, if yes then how?

**Comment by omarelweshy** [comment]
@heyanilthakur I tried to install with yarn and build with npm and it works for me.

![image](https://github.com/user-attachments/assets/2140d3a6-2710-4a56-a817-3f6a48719157)

**Comment by Edamijueda** [comment]
> @heyanilthakur I tried to install with yarn and build with npm and it works for me.
> 
> ![image](https://private-user-images.githubusercontent.com/37350174/354753687-2140d3a6-2710-4a56-a817-3f6a48719157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MTgyOTQsIm5iZiI6MTcyMjcxNzk5NCwicGF0aCI6Ii8zNzM1MDE3NC8zNTQ3NTM2ODctMjE0MGQzYTYtMjcxMC00YTU2LWE4MTctM2Y2YTQ4NzE5MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIwNDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMzZmYjc1ZDk5ODY3ZmJlNTMzZDcwYWZjMjkwMDA3ZmUxMDk5MTkyM2Q4ZjJkMGFjZTBhMWMyOWNkMjY2ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uQT_aLw-D8Kw-8puyxpbO_CDnt6JF_u3oe7R98-kbkw)

Where did you see the Framework preset window that show up?
