### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by asharbinkhalil** [bchiang7/v4#256]
npm start 
is giving this error
![image](https://user-images.githubusercontent.com/68750622/228282797-739d6d6b-6f3e-4698-93ea-42c69cc78ef5.png)
is these some requirements issue or what?
another error after this is
![image](https://user-images.githubusercontent.com/68750622/228283050-cd1f40cf-4665-4d40-b114-231cd32ff8a2.png)

**Comment by alekgomes** [comment]
Hi!
I think you need to run `nvm install`.

**Comment by asharbinkhalil** [comment]
Problem solved by using the correct veriosn of node 
`nvm install <node version>`
`nvm use <node version`
