### ISSUE TITLE
when i run npm build it gives me this error

### ISSUE THREAD

**Issue by CrazyLilOsama** [bchiang7/v4#36]
```
success onPostBootstrap - 0.407s
⠀
info bootstrap finished - 16.349 s
⠀
success Building production JavaScript and CSS bundles - 48.782s
success Rewriting compilation hashes - 0.006s

 ERROR 

UNHANDLED REJECTION /mnt/c/Users/mishr/Project/gatsby/main/v4/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory




  Error: /mnt/c/Users/mishr/Project/gatsby/main/v4/node_modules/cwebp-bin/vendor/cwebp: error while loading shared librar  ies: libGL.so.1: cannot open shared object file: No such file or directory
  
  - index.js:231 
    [v4]/[exec-buffer]/[execa]/index.js:231:11
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - process-file.js:191 
    [v4]/[gatsby-plugin-sharp]/process-file.js:191:7
  
  - async Promise.all
  

not finished run queries - 56.615s
not finished Generating image thumbnails - 5.080s

(sharp:9254): GLib-CRITICAL **: 17:53:34.325: g_hash_table_lookup: assertion 'hash_table != NULL' failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v4@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v4@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/crazylilosama/.npm/_logs/2019-12-04T12_23_34_381Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

```

**Comment by CrazyLilOsama** [comment]
### this is complete terminal log

```
> Executing task: npm run build <


> v4@1.0.0 build /mnt/c/Users/mishr/Project/gatsby/main/v4
> gatsby build

success open and validate gatsby-configs - 0.186s
success load plugins - 3.834s
success onPreInit - 0.035s
success delete html and css files from previous builds - 0.030s
success initialize cache - 0.247s
success copy gatsby files - 1.228s
success onPreBootstrap - 0.024s
success createSchemaCustomization - 0.065s
success source and transform nodes - 1.183s
success building schema - 1.313s
success createPages - 0.035s
success createPagesStatefully - 0.276s
success onPreExtractQueries - 0.033s
success update schema - 0.069s
success extract queries from components - 1.382s
success write out requires - 0.047s
success write out redirect data - 0.007s
success Build manifest and related icons - 0.290s
success onPostBootstrap - 0.407s
⠀
info bootstrap finished - 16.349 s
⠀
success Building production JavaScript and CSS bundles - 48.782s
success Rewriting compilation hashes - 0.006s

 ERROR 

UNHANDLED REJECTION /mnt/c/Users/mishr/Project/gatsby/main/v4/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory




  Error: /mnt/c/Users/mishr/Project/gatsby/main/v4/node_modules/cwebp-bin/vendor/cwebp: error while loading shared librar  ies: libGL.so.1: cannot open shared object file: No such file or directory
  
  - index.js:231 
    [v4]/[exec-buffer]/[execa]/index.js:231:11
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - process-file.js:191 
    [v4]/[gatsby-plugin-sharp]/process-file.js:191:7
  
  - async Promise.all
  

not finished run queries - 56.615s
not finished Generating image thumbnails - 5.080s

(sharp:9254): GLib-CRITICAL **: 17:53:34.325: g_hash_table_lookup: assertion 'hash_table != NULL' failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v4@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v4@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/crazylilosama/.npm/_logs/2019-12-04T12_23_34_381Z-debug.log
The terminal process terminated with exit code: 1

```

**Comment by bchiang7** [comment]
Try removing node modules and running `yarn` again

**Comment by CrazyLilOsama** [comment]
crazylilosama@Yashraj-LEGION:~/temp/v4$ npm start
> v4@1.0.0 start /home/crazylilosama/temp/v4
> npm run develop
> v4@1.0.0 develop /home/crazylilosama/temp/v4
> gatsby develop                                                                                                                                                                                                                                
success open and validate gatsby-configs - 0.085s                                                                       
success load plugins - 1.146s                                                                                           
success onPreInit - 0.012s                                                                                              
success initialize cache - 0.012s                                                                                       
success copy gatsby files - 0.612s                                                                                      
success onPreBootstrap - 0.012s                                                                                         
success createSchemaCustomization - 0.037s                                                                              
success source and transform nodes - 0.519s                                                                             
success building schema - 0.416s                                                                                        
success createPages - 0.042s                                                                                            
success createPagesStatefully - 0.095s                                                                                  
success onPreExtractQueries - 0.002s                                                                                    
success update schema - 0.025s                                                                                          
success extract queries from components - 0.342s                                                                        
success write out requires - 0.069s                                                                                     
success write out redirect data - 0.012s                                                                                
success Build manifest and related icons - 0.127s                                                                       
success onPostBootstrap - 0.182s                                                                                        ⠀                                                                                                                       
info bootstrap finished - 7.294 s                                                                                       ⠀                                                                                                                       
warn code block or inline code language not specified in markdown. applying generic code block                          
success run queries - 3.404s - 14/14 4.11/s                                                                                                                                                                                                     
ERROR                                                                                                                                                                                                                                          
UNHANDLED REJECTION /home/crazylilosama/temp/v4/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
Error: /home/crazylilosama/temp/v4/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so  .1: cannot open shared object file: No such file or directory                                                                                                                                                                                   
- index.js:231 Promise.all.then.arr                                                                                       
[v4]/[exec-buffer]/[execa]/index.js:231:11                                                                                                                                                                                                    
- next_tick.js:68 process._tickCallback                                                                                   
internal/process/next_tick.js:68:7                                                                                                                                                                                                                                                                                                                                  
not finished Generating image thumbnails - 7.795s                                                                                                                                                                                                                                                                                                                       
————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
13 pages                                                  In Progress                                                 v4npm ERR! code ELIFECYCLE                                                                                                
npm ERR! errno 1                                                                                                        
npm ERR! v4@1.0.0 develop: `gatsby develop`                                                                             
npm ERR! Exit status 1                                                                                                  
npm ERR!                                                                                                                
npm ERR! Failed at the v4@1.0.0 develop script.                                                                         
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                              
npm ERR! A complete log of this run can be found in:                                                                    
npm ERR!     /home/crazylilosama/.npm/_logs/2020-01-04T20_56_45_450Z-debug.log                                          
npm ERR! code ELIFECYCLE                                                                                                
npm ERR! errno 1                                                                                                        
npm ERR! v4@1.0.0 start: `npm run develop`                                                                              
npm ERR! Exit status 1                                                                                                  
npm ERR!                                                                                                                
npm ERR! Failed at the v4@1.0.0 start script.                                                                           
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                              
npm ERR! A complete log of this run can be found in:                                                                    
npm ERR!     /home/crazylilosama/.npm/_logs/2020-01-04T20_56_45_486Z-debug.log                                          
crazylilosama@Yashraj-LEGION:~/temp/v4$

**Comment by CrazyLilOsama** [comment]
I am using wsl **Ubuntu** on **_Windows_**
