### ISSUE TITLE
Changing the logo image in loader, favicon and title

### ISSUE THREAD

**Issue by Remorax** [bchiang7/v4#38]
Hi,
Can someone please tell me how to change the Hexagonal "B" logo and insert my own logo? As in, where do I put the new image and/or what parts of the code do I modify for the same?
Any pointers would be helpful.

Also, I have already changed `logo.png` in `/images/` folder and the favicons in the `/images/favicons/`  and the favicon does change, but on restarting the server, the original logo is again written to .cache for some reason. Any way to stop this?

**Comment by bchiang7** [comment]
The logo is an SVG I created and exported in Sketch https://github.com/bchiang7/v4/blob/master/src/components/icons/logo.js

**Comment by Remorax** [comment]
Perfect, that helped me solve my issue. Thank you so much for your help and for this amazing website, you're the best! <3

**Comment by ojsimon** [comment]
Hi @bchiang7 ,

I am trying to change the letter in the Loading screen from B to an O. How can I do this? I cannot see any B in the loader.js file. Where is the animation in the codebase?

Thanks

**Comment by abhishek-t-naive** [comment]
@Remorax Is it possible for you to highlight how you went about changing the logo during the website loading?

**Comment by xamantra** [comment]
@abhishek-t-naive you can do it with `text` element on svg. Refer to this [comment](https://github.com/bchiang7/v4/issues/54#issuecomment-636045344)

**Comment by abhishek-t-naive** [comment]
@xamantra This worked perfectly. Have you tried designing a completely new logo and utilising it here?

**Comment by xamantra** [comment]
@abhishek-t-naive , nope. I'm not a designer type of guy really. That's why I give up on editing the svg graphic and search for alternative and I found `text` element :)

**Comment by abhishek-t-naive** [comment]
Makes sense. Thanks for sharing it.

**Comment by abhishek-t-naive** [comment]
Sorry, but what exactly you mean by you photoshopped it? Did you create it in photoshop?

**Comment by abhishek-t-naive** [comment]
@xamantra   Sorry, but what exactly you mean by you photoshopped it? Did you create it in photoshop?

**Comment by xamantra** [comment]
@abhishek-t-naive 
More like edited on photoshop. I just replaced the letter from the original logo.

**Comment by abhishek-t-naive** [comment]
Okay. I will try that

**Comment by abhishek-t-naive** [comment]
@xamantra I actually created a new logo with Inkscape and that seems to work great. Your suggestion of using `<text>` is a pretty simple and straightforward one for anyone who is not trying to fiddle around much with the website.

As we are on the topic, do you know how can I increase the size of the logo displayed in the top left corner?

I feel that it must be a part of a section which will need changes to its dimensions to change size of the logo. I am not too familiar with CSS, hence I would appreciate if you can point me in the right direction
