### ISSUE TITLE
Changing the B letter in the loader screen?

### ISSUE THREAD

**Issue by ojsimon** [bchiang7/v4#54]
Hi @bchiang7 ,

I am trying to change the letter in the Loading screen from B to an O. How can I do this? I cannot see any B in the loader.js file. Where is the animation in the codebase?

Thanks

**Comment by bchiang7** [comment]
Hey @ojsimon, the logo is an SVG I made then exported from Sketch. It lives here https://github.com/bchiang7/v4/blob/master/src/components/icons/loader.js

**Comment by ojsimon** [comment]
@bchiang7 is there an easy way to remove the loader completely and just go straight to the homepage?

**Comment by bchiang7** [comment]
You would need to modify `layout.js` to not use the loading state

**Comment by adityavverma** [comment]
Hi, can you help me with the svg of letter A or suggest me a guide.
Thanks!

**Comment by xamantra** [comment]
I know this is already closed but I was able to replace the letter **B** with `text` element on svg instead of `path`.
```xml
        <text x="26" y="57" fill="currentColor" fontSize="50px" fontFamily="Consolas, serif">
          x
        </text>
```
You can do this on both *components/icons/* `loader.js` and `logo.js`.
