### ISSUE TITLE
TypeError: tech is null

### ISSUE THREAD

**Issue by snowiesuet** [bchiang7/v4#66]
Thank you @bchiang7 for making this portfolio template and having it open sourced! :)

I encountered an error when trying to run this locally for the first time. 
I got this error:
`TypeError: tech is null` in project.js
The error is coming from:
```
  <StyledTechList>
    {tech.map((tech, i) => (
       <li key={i}>{tech}</li>
     ))}
  </StyledTechList>

```
I looked at featured.js and that seems to be working so I just copied over to project.js and that did the trick!

```
{tech && (
    <StyledTechList>
        {tech.map((tech, i) => (
           <li key={i}>{tech}</li>
            ))}
     </StyledTechList>
  )}
```
Not sure if it is intended or missed out by accident!

**Comment by bchiang7** [comment]
Hey @snowiesuet, I don't seem to be experiencing this error, but your suggested fix doesn't hurt!
