### ISSUE TITLE
Active jobs tab highlight on mobile

### ISSUE THREAD

**Issue by alleyhector** [bchiang7/v4#71]
Firstly, amazing template. Thanks so much for making it available.

I've noticed that on mobile the active tabs in the jobs section the highlight doesn't always line up with the tab. As it seems to get worse the farther right you go I'm guessing it's a small math error that grows as it goes. But I haven't actually started troubleshooting this at all so that's just a guess at this point. I plan to, and if I figure it out quickly I'll go ahead and let you know and close this out but I thought it might be nice to get your perspective too.

<img width="234" alt="Screen Shot 2020-05-12 at 6 10 05 PM" src="https://user-images.githubusercontent.com/1653653/81761798-c0863600-947f-11ea-9fed-e0184394b229.png">

(Thanks again)

**Comment by alleyhector** [comment]
When I realized that mobile devices just used a set width from the theme.js I _think_ I'm pretty much decided to just make that a little wider and my text a little shorter, but I am still kind of curious would it would be to dynamically place the highlight based on a dynamic width of the button and text.

**Comment by bchiang7** [comment]
Yeah, using a fixed with for horizontal tabs was intentional for my use case, since all of my tab text is pretty uniform in length. Dynamically changing the highlight width in position would definitely require more math!

**Comment by alleyhector** [comment]
Well I'm happy to close this or we could leave it open in case anyone else has this question and wants to tackle it with me. Either way. Thanks for responding.

**Comment by bchiang7** [comment]
👍 closing!
