### ISSUE TITLE
Support to add blogs

### ISSUE THREAD

**Issue by kushthedude** [bchiang7/v4#73]
Gatsby supports the addition of blogs & documentation to its framework.
Does this template can also support blogs?

**Comment by kushthedude** [comment]
Hi @bchiang7 , Great design you have created here! I was going to create my portfolio from scratch but after seeing this portfolio, I couldn't resist myself to make a fork of it. I hope you don't have any objections if I use this template. Considering the original design is proprietory of your https://github.com/kushthedude/kushthedude.co, please let me know if there are any objections.
Also can this template support blog posts?

**Comment by bchiang7** [comment]
Hi @kushthedude, to be clear this repo is for my personal site -- it's not meant to be a template! However it does support the concept of "posts" [here](https://github.com/bchiang7/v4/tree/master/content/posts)

**Comment by kushthedude** [comment]
Thanks for your reply @bchiang7 , Can we use this site as a portfolio without removing your proprietary logo in the bottom which redirects to the original repository? Please let me know if using the site with giving design & building credits to you is liable or not .

**Comment by bchiang7** [comment]
Obviously I would appreciate it if you gave me credit! Please see the [readme](https://github.com/bchiang7/v4#-forking-this-repo-please-read)

**Comment by kushthedude** [comment]
> Obviously I would appreciate it if you gave me credit! Please see the [readme](https://github.com/bchiang7/v4#-forking-this-repo-please-read)

Thanks for creating such a wonderful portfolio website.

**Comment by siddhpurakaran** [comment]
> Hi @kushthedude, to be clear this repo is for my personal site -- it's not meant to be a template! However it does support the concept of "posts" [here](https://github.com/bchiang7/v4/tree/master/content/posts)

what will be url of that posts ?
something like this : xyz.github.io/posts/post1

**Comment by Caruso33** [comment]
@siddhpurakaran  The content/posts markdowns are reachable at http://localhost:8000/pensieve/  and the single posts then like e.g. http://localhost:8000/pensieve/docker-error.

The react component you find at pages/pensieve directory.
