### ISSUE TITLE
Adding new icons

### ISSUE THREAD

**Issue by abhishek-t-naive** [bchiang7/v4#75]
Hi,
First of all, congratulations on the website. It looks really good.

I have been thinking of utilising the same as my own personal website (credited to you!). I was wondering how do I go about adding a new icon, say youtube, to the list of icons in 

`src/components/icons.`

I downloaded an SVG file for the same and converted it to .js file (do you recommend a particular method of doing that?) which is now present as youtube.js at 
`src/components/icons.` 

I also added the same in formattedIcon.js and I thought it will be good to go as:

`youtube: 'https://www.youtube.com/watch?v=pYe77UhBgKg'`

But I am still not able to get the youtube-icon below my project. I would welcome your suggestions

**Comment by bchiang7** [comment]
Hey @abhishek-t-naive, It's hard for me to help you without seeing any code! My only suggestion is to double-check your spelling?

**Comment by abhishek-t-naive** [comment]
Aah! I should have shared my repo with you.

https://github.com/abhishek-t-naive/v4

Here I have posted the most recent version of what I have been working on. The structure is the same as your website. 

Moreover, I would like to know from you if there is a specific format in which .js files should be. I am a novice when it comes to JS, so I am not aware. As I don't use a Mac, I can't use Sketch to generate a logo. I tried using Inkscape to generate an SVG file which I converted to a .JS file using  [this](https://svg2jsx.com/) but that didn't work just like with the youtube-icon.

Is it possible for you to point out any particulars while trying to add new icons, logos or other .js files?

**Comment by bchiang7** [comment]
Just took a quick look and it looks like there's nothing wrong with the youtube icon. Is there any more context you can provide?

**Comment by abhishek-t-naive** [comment]
I am not sure if I have anything else to add to this. 
I am using:
`.nvm/versions/node/v12.16.2/` on Ubuntu 18.04

Is it possible for you to try out the Youtube icon integration on your end to see if it a system-specific issue?

**Comment by bchiang7** [comment]
Hey @abhishek-t-naive I cloned your repo and added youtube as a social media item in [config.js](https://github.com/abhishek-t-naive/v4/blob/master/src/config.js#L16) -- it seemed to show up fine?

![image](https://user-images.githubusercontent.com/6599979/82834932-8a3db300-9e90-11ea-87dd-f9e7587572f7.png)

Note that I had to comment out the [`cover` graphql query](https://github.com/abhishek-t-naive/v4/blob/master/src/pages/index.js#L90-L96) first in order to get the site to run

**Comment by abhishek-t-naive** [comment]
The above is working fine for me as well in config.js. But if you have a look at the file [index.md](https://github.com/abhishek-t-naive/v4/blob/master/content/featured/GloveAbove/index.md), I am trying to display the icon along with the github and external website icon. 

My apologies, I don't think I presented you with the actual file with the problem before

**Comment by bchiang7** [comment]
Gotcha, you'd have to add `youtube` to the [GraphQL query](https://github.com/abhishek-t-naive/v4/blob/master/src/pages/index.js#L98) and pull it into the [Featured component](https://github.com/abhishek-t-naive/v4/blob/master/src/components/sections/featured.js#L225)

**Comment by abhishek-t-naive** [comment]
Yeah, this worked perfectly. With the above changes, I also modified other section of [Featured component](https://github.com/abhishek-t-naive/v4/blob/887f7e212d6918deac2044afe2400c276fa1659a/src/components/sections/featured.js#L271). Thank you!

Before we close the issue, I would just like to ask you that to replace the logo at the start, do I just need to make replace the [loader.js](https://github.com/abhishek-t-naive/v4/blob/887f7e212d6918deac2044afe2400c276fa1659a/src/components/icons/loader.js#L3) with that of the new logo or are there more places to make changes to?
[You can ignore this if it is something that I am supposed to figure out myself, considering that you did not design the website as a template]

**Comment by bchiang7** [comment]
You'd also have to change `IconLogo` in the nav. Glad you figured it out!

**Comment by abhishek-t-naive** [comment]
> Hey @abhishek-t-naive I cloned your repo and added youtube as a social media item in [config.js](https://github.com/abhishek-t-naive/v4/blob/master/src/config.js#L16) -- it seemed to show up fine?
> 
> ![image](https://user-images.githubusercontent.com/6599979/82834932-8a3db300-9e90-11ea-87dd-f9e7587572f7.png)
> 
> Note that I had to comment out the [`cover` graphql query](https://github.com/abhishek-t-naive/v4/blob/master/src/pages/index.js#L90-L96) first in order to get the site to run

Hey @bchiang7 , why did you have to comment out the 'cover' graphql query in order to get the site to run?

**Comment by bchiang7** [comment]
it was throwing an error for me
