### ISSUE TITLE
Post Content is Mixed up in projects part , achived project route not working

### ISSUE THREAD

**Issue by jarviotdev** [bchiang7/v4#76]
post content is mixed up with project content and UI is collapsed if I delete posts, and achive route is also not working
![Screenshot from 2020-05-24 00-05-31](https://user-images.githubusercontent.com/52395184/82738110-0500b400-9d53-11ea-9255-4eb7a15450c3.png)
![Screenshot from 2020-05-24 00-12-00](https://user-images.githubusercontent.com/52395184/82738146-409b7e00-9d53-11ea-9b10-f64e22711011.png)

, could you please tell me how to fix it 
thank you 
you made a great portfolio

**Comment by bchiang7** [comment]
Hi @jarviotdev, it's hard for me to help without seeing any code. Is this happening on a fresh install?

**Comment by jarviotdev** [comment]
@bchiang7 yes it's happening on a fresh install, i have tried more than twice

**Comment by bchiang7** [comment]
I can't seem to reproduce this problem, could you provide any more details?

**Comment by jarviotdev** [comment]
Could you please fresh install from git in other directory error is in graphql query , or could you just add it on any other platform , it giving lots of error
![Screenshot from 2020-05-25 23-03-30](https://user-images.githubusercontent.com/52395184/82833696-6c963b00-9edc-11ea-9cbf-f34f54913c9b.png)
see error in graphql querys

**Comment by bchiang7** [comment]
Hi @jarviotdev could you point me to a repository where you're experiencing this error? I've tried a fresh install in another directory, and I still can't reproduce the problem

**Comment by jarviotdev** [comment]
error fixed after in fulol regex search i replaced 
"projects" with "content/projects"
