### ISSUE TITLE
ERROR #85922 GRAPHQL: There was an error in your GraphQL query

### ISSUE THREAD

**Issue by jaredbest** [bchiang7/v4#77]
I am trying to build and deploy this site but receive the following error after running _npm start:_

**Repo:** https://github.com/jaredbest/personal-website

~~~~
ERROR #85922  GRAPHQL
There was an error in your GraphQL query:
Field "avatar" must not have a selection since type "String" has no subfields.
This can happen if you e.g. accidentally added { } to the field "avatar". If you didn't expect "avatar" to be of type "String" make sure that your input source and/or plugin is correct.
File: src/pages/index.js:52:20
~~~~

I am using a computer running Pop! OS. On Windows 10, I don't receive this error message and can start the development server.

Do you know what the issue is? Thank you, and amazing work on this!

**Comment by bchiang7** [comment]
Looks like you capitalized `.JPG` https://raw.githubusercontent.com/jaredbest/personal-website/master/content/about/index.md

`avatar: './me.jpg'` should work.

I'd appreciate it if you gave me credit on your site, not just your GitHub repo!

**Comment by jaredbest** [comment]
Thanks for the super fast response, and I can't believe I missed that. Thanks again!

And of course! I was planning to update footer.js to include a link to your website before deploying as the original footer I had was incorrect. Now it's done!
