### ISSUE TITLE
Error - The system cannot find the path specified.

### ISSUE THREAD

**Issue by TheDudeThatCode** [bchiang7/v4#79]
@bchiang7  Mam when I am doing npm start I am getting the following error, please help me 

> Executing task: npm run start <

> v4@1.0.0 start C:\Users\SHUBHAMDEEP JHA\Desktop\v4-master
> npm run develop

> v4@1.0.0 develop C:\Users\SHUBHAMDEEP JHA\Desktop\v4-master
> gatsby develop

success open and validate gatsby-configs - 0.120s
success load plugins - 3.381s
success onPreInit - 0.027s
success initialize cache - 0.029s
success copy gatsby files - 0.249s
success onPreBootstrap - 0.031s
success createSchemaCustomization - 0.098s
success source and transform nodes - 1.696s
success building schema - 0.839s
success createPages - 0.153s
success createPagesStatefully - 0.294s
success onPreExtractQueries - 0.004s
success update schema - 0.088s   
success extract queries from components - 1.171s
success write out requires - 0.191s
success write out redirect data - 0.075s
success Build manifest and related icons - 0.339s
success onPostBootstrap - 0.358s
⠀
info bootstrap finished - 16.307s
⠀
warn code block or inline code language not specified in markdown. applying generic code block
success run queries - 10.182s - 14/14 1.38/s

 ERROR 

Processing C:/Users/SHUBHAMDEEP JHA/Desktop/v4-master/content/featured/SpotifyProfile/demo.png failed

Original error:
The system cannot find the path specified.

  WorkerError: Processing C:/Users/SHUBHAMDEEP JHA/Desktop/v4-master/content/featured/SpotifyProfile/demo.png failed
  Original error:
  The system cannot find the path specified.

  - jobs-manager.js:316 exports.enqueueJob
    [v4-master]/[gatsby]/dist/utils/jobs-manager.js:316:23

not finished Generating image thumbnails - 18.769s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v4@1.0.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v4@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SHUBHAMDEEP JHA\AppData\Roaming\npm-cache\_logs\2020-05-31T13_42_18_163Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v4@1.0.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v4@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SHUBHAMDEEP JHA\AppData\Roaming\npm-cache\_logs\2020-05-31T13_42_18_446Z-debug.log
The terminal process terminated with exit code: 1

![image](https://user-images.githubusercontent.com/41606999/83354724-2166a700-a378-11ea-9ea3-f624f02159fd.png)

**Comment by TheDudeThatCode** [comment]
Mam pls check this out this website, someone has copied your website

https://ishanchhabra.com/

![IMG_20200601_231029](https://user-images.githubusercontent.com/41606999/83437324-3701cc80-a45d-11ea-8df6-4a7cfc1407ac.jpg)

**Comment by TheDudeThatCode** [comment]
@bchiang7

**Comment by siddhpurakaran** [comment]
i am also getting the same.
Tell me if if you have solved it. 
@TheDudeThatCode
