### ISSUE TITLE
Can you share the source file of your pdf resume?

### ISSUE THREAD

**Issue by expl0ring** [bchiang7/v4#8]
Hey bchiang,

I really liked your resume template, both web one and pdf one. Can I use this for mine?

Can you share the editable template or source file specially of resume.pdf one? Weather it's adobe indesign or docs or whatever. I'm in love, the placement you designed was really fabulous. I'm seeking for job, and this will definitely help me.

**Comment by expl0ring** [comment]
Hello @bchiang7, Do you mind sharing your resume's source file?

**Comment by bchiang7** [comment]
I'm currently not giving out the template for my resume, but you are free to try to replicate it yourself! I made it using Sketch, but there are many tools like InDesign or Canva that you can use to achieve the same thing. Good luck!
