### ISSUE TITLE
Changing sections heading and adding more sections

### ISSUE THREAD

**Issue by abhishek-t-naive** [bchiang7/v4#83]
Hi,
I have been tinkering with the website and want to use it as a base for my own. I was wondering if it would be possible for you to highlight two things:
1. If I want to change the headings (like 'About me' , 'Where I've Worked' etc) to something different, where can I find the same to be changed?
2. If I want to add more sections, like ones for Publications, should they go in the content directory?
3. As the website is divided into sections (01 About me,02 Where I've Worked,03...), I have been thinking of changing the background colour of each of these sections. Can you comment on it, if possible?

I would appreciate your inputs

**Comment by abhishek-t-naive** [comment]
@bchiang7 Is it possible for you to comment on the above queries?

**Comment by bchiang7** [comment]
1. The section headings are editable via the `title` frontmatter fields in their respective markdown files
2. That's up to you
3. The navy background color is set on the `<body>`, but you could give a background color for each `<section>`. You'd have to change where some padding is set let the different colors go full width though

**Comment by abhishek-t-naive** [comment]
Thanks for the tips. It solved my issue! I will share my website once I am done.
