### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by OjasviChauhan** [bchiang7/v4#85]
When I am replacing a previous image (for eg: octoprofile), located in the content, with my new image having the same name, it throws an error saying:
**"TypeError: Cannot read property 'childImageSharp' of null"** 
at location _v4/src/components/sections/featured.js:278_: 
`<StyledFeaturedImg fluid={cover.childImageSharp.fluid} alt={title} />`

All the suggestions would be appreciated

**Comment by polarathene** [comment]
It's a Gatsby issue. You need to ensure the frontmatter data provides the `fluid` data object from `gatsby-plugin-sharp`, you can see  the `cover` object is destructured here:

https://github.com/bchiang7/v4/blob/b54557d9ba842ae74bc8778dd21bd764b3009ff5/src/components/sections/featured.js#L225

If it's null, then something didn't go right with processing the images. For `OctoProfile`, you're replacing this: `cover: './octoprofile.png'`. If you provided a png image that replaces it with the same filename, then there should be an error about why sharp failed to process the image.
