### ISSUE TITLE
Issue with image (avatar)

### ISSUE THREAD

**Issue by abhishek-t-naive** [bchiang7/v4#93]
Hi
I have been working with your website for a while and I am almost done with the first version of my own. Everything was working great but suddenly the photo of me is getting screwed up.
The idea is to have a transparent shadow on top of the image before hovering. You can check my current website [here](https://abhishek-t-naive.github.io/portfolio/). So, do so I believe I have to make changes to about.js file which I have done as [here](https://github.com/abhishek-t-naive/portfolio/blob/3b263c2ef474f3b996c1fe53a8fc672c1bebae06/src/components/sections/about.js#L80)

But still, I am not getting the desired results. I was successfully able to get it working once, but could not push the entire thing. Any help would be appreciated

**Comment by bchiang7** [comment]
From a glance it looks like the Gatsby image component is using the traced SVG version of the image -- nothing to do with CSS?

**Comment by abhishek-t-naive** [comment]
I don't think it has much to do with CSS. I have tried the different color combinations for the background color of the image but to no effect. 
I think it might be related to the Gatsby image component is using the traced SVG version of the image. Is it possible for you to point where this might have gone wrong?

**Comment by abhishek-t-naive** [comment]
Also, if it is a traced version before the hover, shouldn't it come back to the normal state after I hover on the image?

**Comment by bchiang7** [comment]
It's hard for to help without seeing any code. Regardless, when I am having trouble with Gatsby Image, I always clear the cache and rebuild the thumbnails.

```sh
rm -rf .cache
npm run build
```

**Comment by abhishek-t-naive** [comment]
I did try this but to no avail. I will see if I can find the issue by comparing it with the original codebase and will update here

**Comment by abhishek-t-naive** [comment]
Okay. So what I found is: When I run my website locally using `npm start` I see all the changes in the correct manner (whether it is the avatar image or the loading of the logo).
But while doing a  `npm build && npm deploy`, I am not able to see the same behavior. Does this help in identifying what the issue might be?

**Comment by bchiang7** [comment]
My best guess as to why Gatsby Image is only loading the traced SVG versions because the actual image files (JPG/PNG) are missing from your github pages branch, or there are permission issues. For example, the URL of the avatar image in the `src` attribute of the `<img>` tag is https://abhishek-t-naive.github.io/static/5d50da9f4ba27decbaf57717a1b71e33/ea4ab/me.jpg, but if you visit that link, it 404s.

**Comment by abhishek-t-naive** [comment]
Okay. I will try to sort this out then

**Comment by abhishek-t-naive** [comment]
So I was able to fix the issue. I looked at the comments [here](https://github.com/gatsbyjs/gatsby/issues/13656) and now before deploying to github pages I run `rm -rf .cache && reset && yarn build && npm run deploy`.

The logo is still not getting loaded when the website is deployed on gh-pages. So I will look into that, but I think @bchiang7 you can close this issue. 

Thank you for your inputs
