### ISSUE TITLE
Problems with Gatsby

### ISSUE THREAD

**Issue by IndhujaRavi** [bchiang7/v4#98]
Hi @bchiang7 ,
Thank you for making our lives easier by building this amazing portfolio and letting us re-use it. However, the following error is making my life so hard now.

I had the application running in my local perfectly but after installing gh-pages to deploy it on github pages, the application stopped running in local as well. Now even if I remove node_modules and package_lock.json and reinstall everything, it still gives me this error when I do npm start. 

> v4@1.0.0 start /Users/indhujaravi/SJSU/Courses/v4
> npm run develop

> v4@1.0.0 develop /Users/indhujaravi/SJSU/Courses/v4
> gatsby develop

 ERROR 

UNHANDLED REJECTION Reducers may not dispatch actions.

  Error: Reducers may not dispatch actions.
  
  - redux.js:214 dispatch
    [v4]/[redux]/lib/redux.js:214:13
  
  - index.js:64 action
    [v4]/[gatsby]/dist/redux/index.js:64:88
  
  - index.js:14 Object.dispatch
    [v4]/[redux-thunk]/lib/index.js:14:16
  
  - index.js:47 dispatch
    [v4]/[gatsby-cli]/lib/reporter/redux/index.js:47:11
  
  - redux.js:483 Object.createLog
    [v4]/[redux]/lib/redux.js:483:12
  
  - index.js:69 Object.text [as log]
    [v4]/[gatsby-cli]/lib/reporter/index.js:69:53
  
  - index.js:461 Console.console.log.args [as log]
    [v4]/[gatsby-cli]/lib/reporter/index.js:461:37
  
  - config.js:20 module.exports
    [v4]/[gatsby]/dist/redux/reducers/config.js:20:19
  
  - redux.js:465 combination
    [v4]/[redux]/lib/redux.js:465:29
  
  - redux.js:219 dispatch
    [v4]/[redux]/lib/redux.js:219:22
  
  - index.js:64 action
    [v4]/[gatsby]/dist/redux/index.js:64:88
  
  - index.js:14 Object.dispatch
    [v4]/[redux-thunk]/lib/index.js:14:16
  
  - index.js:170 module.exports
    [v4]/[gatsby]/dist/bootstrap/index.js:170:9
  

not finished open and validate gatsby-configs - 0.101s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v4@1.0.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v4@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/indhujaravi/.npm/_logs/2020-09-20T01_54_11_735Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v4@1.0.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v4@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/indhujaravi/.npm/_logs/2020-09-20T01_54_11_758Z-debug.log

**Comment by bchiang7** [comment]
Hi @IndhujaRavi, sorry for the late response -- are you still having problems?

**Comment by Kunalyash** [comment]
I am also facing the same issue

**Comment by Stratonov16** [comment]
> Hi @IndhujaRavi, sorry for the late response -- are you still having problems?

Yes I am having this issue as well.
